KeepAlive.yml Updated

diff --git a/.github/workflows/keepalive.yml b/.github/workflows/keepalive.yml
--- a/.github/workflows/keepalive.yml
+++ b/.github/workflows/keepalive.yml
@@ -9,7 +9,8 @@ jobs:
   ping:
     runs-on: ubuntu-latest
     steps:
-      - name: Ping Scrapyd
+      - name: Ping Scrapyd Backends
         run: |
           echo "Pinging Scrapyd at $(date)"
-          curl -s https://jobapp-bah2.onrender.com/daemonstatus.json || echo "Ping failed"
+          curl -s https://jobapp-backend-25kl.onrender.com/ || echo "Ping to jobapp-backend failed"
+          curl -s https://jobapp-bah2.onrender.com/daemonstatus.json || echo "Ping to jobapp-bah2 failed"
