Uncomment CI/CD steps in scrapyd workflow

diff --git a/.github/workflows/scrapyd-ci-cd.yml b/.github/workflows/scrapyd-ci-cd.yml
--- a/.github/workflows/scrapyd-ci-cd.yml
+++ b/.github/workflows/scrapyd-ci-cd.yml
@@ -13,25 +13,25 @@ jobs:
     runs-on: ubuntu-latest  
 
     steps:  
-      # - name: Checkout repository  
-      #   uses: actions/checkout@v3  
+      - name: Checkout repository  
+        uses: actions/checkout@v3  
 
-      # - name: Set up Python  
-      #   uses: actions/setup-python@v4  
-      #   with:  
-      #     python-version: '3.11'  
+      - name: Set up Python  
+        uses: actions/setup-python@v4  
+        with:  
+          python-version: '3.11'  
 
-      # - name: Install dependencies  
-      #   working-directory: ./newscraper  
-        # run: |  
-        #   python -m pip install --upgrade pip  
-        #   pip install -r requirements.txt  
-        #   pip install scrapyd-client  
+      - name: Install dependencies  
+        working-directory: ./newscraper  
+        run: |  
+          python -m pip install --upgrade pip  
+          pip install -r requirements.txt  
+          pip install scrapyd-client  
 
-      # - name: Deploy to Scrapyd  
-      #   working-directory: ./newscraper/jobscrapper  
-      #   run: |  
-      #     scrapyd-deploy jobscrapper  
+      - name: Deploy to Scrapyd  
+        working-directory: ./newscraper/jobscrapper  
+        run: |  
+          scrapyd-deploy jobscrapper  
 
       - name: Ping WorkoutBuddy Backends  
         run: |  
@@ -39,7 +39,7 @@ jobs:
           curl -s https://workoutbuddy-9nqn.onrender.com/ || echo "Ping to workoutBuddy-backend failed"  
           curl -s https://workoutbuddyfrontend-kn9e.onrender.com/ || echo "Ping to workoutBuddy-Frontend failed"  
 
-      # - name: Ping Other Scrapyd Backends  
-      #   run: |  
-      #     curl -s https://jobapp-backend-25kl.onrender.com/ || echo "Ping to jobapp-backend failed"  
-      #     curl -s https://jobapp-bah2.onrender.com/daemonstatus.json || echo "Ping to jobapp-bah2 failed"
+      - name: Ping Other Scrapyd Backends  
+       run: |  
+          curl -s https://jobapp-backend-25kl.onrender.com/ || echo "Ping to jobapp-backend failed"  
+          curl -s https://jobapp-bah2.onrender.com/daemonstatus.json || echo "Ping to jobapp-bah2 failed"
